apiVersion: v1
kind: Pod
metadata:
  name: http-server
  labels:
    app: http-server
spec:
  containers:
  - name: http-server
    image: andyrunrunrun/quiz-server
    ports:
    - containerPort: 8080

